### ISSUE TITLE
Button UI improvements

### ISSUE THREAD

**Issue by TeddyBearX** [CuBoulder/ucb_ckeditor_plugins#22]
- Pressing the Escape key should close/cancel the UI as it does with Map.
- Does it make sense to have "Default" and "Full" swap places?
- An "Edit contents" button can exist in the UI for focusing the inner contents field.
- ~With a parent element check, the UI can be made to appear when the inner contents are focused. Pressing "Save" immediately moves the selection to the outer widget regardless of what's currently selected, to make it behave correctly in replacing the outer widget. This eliminates the need for things like extra padding as pressing anywhere on the button is expected to make the UI appear.~ Having second thoughts about this one, especially in terms of difficulty. And with the expected behavior being to have the link field focused when showing the UI, this is not going to be the case if the contents are focused instead.

**Comment by patrickbrown-io** [comment]
Definitely agree with 1 and 2. 

I'm not sold on the idea of adding an edit contents button - when a user is creating a new button, the Edit Contents button wouldn't focus since the created button doesn't exist yet and there's no inner text field to focus to. 

After save it automatically moves the focus to the inner text field, or just one click on the text to edit contents from the editor if the button already exists. With a button just for this in the UI, it would add an extra user step to click to access the UI and then click Contents button, just to focus the inner text which can already be done faster using the other routes. 

Thoughts @jcsparks ?

**Comment by TeddyBearX** [comment]
The "Edit contents" would be missing or disabled when creating a new one. My only concern is there's no visual indication that clicking on the contents does anything different from clicking on the outer padding.

**Comment by TeddyBearX** [comment]
This is a non-issue if we expect folks to read the documentation – not unreasonable!
