### ISSUE TITLE
Count Up Shortcode

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/ucb_ckeditor_plugins#66]
First the count up shortcode goes way too fast for small numbers - can we slow it down for 100 and less?
Second when you add a time 21:45:00 - it only counts up the hours  - I don't think this is a typical use case but I wanted to mention it since we said that the code will work for time. The documentation also says it works for formatted numbers such as 1,234,567.00 but does not.
D7 documentations says "The Count Up shortcode supports counting up with integers (12345), floats (0.1234), formatted numbers (1,234,567.00), and time (21:45:00)." Let me know if it should work with these other formats or if it only will work with integers. I am updating the documentation.

**Comment by jnicholCU** [comment]
@ekellagher I have an update that's under review right now but I have updated our code so that it works as the D7 information states it does. I was actually getting errors in my D7 testing too so I updated us to the newer open source code that is being used in D7. 

For the the time specifically it will now count up the hours/minutes/seconds simultaneously but separate. I couldn't get it to work at all in D7. 

Once this gets merged in you should see it reflected in the next sandbox updates.
